package com.troy.hanguang.sysservice.dao;

import com.troy.hanguang.sysservice.bean.SysUser;
import com.troy.hanguang.sysservice.bean.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    long countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sys_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sys_user (id, login_name, ",
        "zh_name, en_name, ",
        "sex, birth, email, ",
        "phone, address, ",
        "password, password_salt, ",
        "rank, create_time, ",
        "update_time, create_by, ",
        "update_by, status, ",
        "is_final)",
        "values (#{id,jdbcType=BIGINT}, #{loginName,jdbcType=VARCHAR}, ",
        "#{zhName,jdbcType=VARCHAR}, #{enName,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=INTEGER}, #{birth,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{passwordSalt,jdbcType=VARCHAR}, ",
        "#{rank,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=BIGINT}, ",
        "#{updateBy,jdbcType=BIGINT}, #{status,jdbcType=TINYINT}, ",
        "#{isFinal,jdbcType=TINYINT})"
    })
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, login_name, zh_name, en_name, sex, birth, email, phone, address, password, ",
        "password_salt, rank, create_time, update_time, create_by, update_by, status, ",
        "is_final",
        "from sys_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.troy.hanguang.sysservice.dao.SysUserMapper.BaseResultMap")
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Update({
        "update sys_user",
        "set login_name = #{loginName,jdbcType=VARCHAR},",
          "zh_name = #{zhName,jdbcType=VARCHAR},",
          "en_name = #{enName,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "birth = #{birth,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "password_salt = #{passwordSalt,jdbcType=VARCHAR},",
          "rank = #{rank,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=BIGINT},",
          "update_by = #{updateBy,jdbcType=BIGINT},",
          "status = #{status,jdbcType=TINYINT},",
          "is_final = #{isFinal,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SysUser record);
}